package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"text/tabwriter"
	"time"

	"github.com/marcfargas/bifrost/pkg/protocol"
	"github.com/spf13/cobra"
)

func newPeerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "peer",
		Short: "Manage federation peers",
	}
	cmd.AddCommand(newPeerNewCmd())
	cmd.AddCommand(newPeerJoinCmd())
	cmd.AddCommand(newPeerListCmd())
	return cmd
}

func newPeerNewCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "new",
		Short: "Generate a magic code for federation peering",
		Long:  "Generates a magic code and announces this hub on the DHT.\nShare the code with another hub operator to establish federation.",
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()

			conn, err := tryHubConnect()
			if err != nil {
				return fmt.Errorf("cannot connect to hub: %w", err)
			}
			defer conn.Close()

			mux := newCLIMux(ctx, conn)

			resp, err := mux.rpcCall(ctx, "peer.new", nil)
			if err != nil {
				return err
			}
			if resp.Error != nil {
				return fmt.Errorf("hub error: %s", resp.Error.Message)
			}

			data, err := json.Marshal(resp.Result)
			if err != nil {
				return fmt.Errorf("marshal result: %w", err)
			}

			var result struct {
				Code string `json:"code"`
			}
			if err := json.Unmarshal(data, &result); err != nil {
				return fmt.Errorf("parse response: %w", err)
			}

			fmt.Println()
			fmt.Println("  Magic code generated. Share this code with the other hub:")
			fmt.Println()
			fmt.Printf("    %s\n", result.Code)
			fmt.Println()
			fmt.Println("  On the other machine, run:")
			fmt.Printf("    bifrost peer join %s\n", result.Code)
			fmt.Println()
			fmt.Println("  The code expires in 24 hours.")
			fmt.Println()

			return nil
		},
	}
}

func newPeerJoinCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "join CODE",
		Short: "Join a federated hub using a magic code",
		Long:  "Connects to a remote hub using the magic code generated by 'bifrost peer new'.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			code := args[0]

			ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
			defer cancel()

			conn, err := tryHubConnect()
			if err != nil {
				return fmt.Errorf("cannot connect to hub: %w", err)
			}
			defer conn.Close()

			mux := newCLIMux(ctx, conn)

			params := map[string]string{"code": code}
			resp, err := mux.rpcCall(ctx, "peer.join", params)
			if err != nil {
				return err
			}
			if resp.Error != nil {
				return fmt.Errorf("hub error: %s", resp.Error.Message)
			}

			data, err := json.Marshal(resp.Result)
			if err != nil {
				return fmt.Errorf("marshal result: %w", err)
			}

			var result struct {
				PeerID string           `json:"peer_id"`
				Agents []protocol.Agent `json:"agents"`
			}
			if err := json.Unmarshal(data, &result); err != nil {
				return fmt.Errorf("parse response: %w", err)
			}

			fmt.Println()
			fmt.Printf("  Connected to peer: %s\n", result.PeerID)
			fmt.Println()

			if len(result.Agents) > 0 {
				fmt.Println("  Remote agents:")
				w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
				fmt.Fprintf(w, "    NAME\tSTATUS\tHOSTNAME\tPATH\n")
				for _, a := range result.Agents {
					name := a.AgentID
					if len(a.Aliases) > 0 {
						name = a.Aliases[0]
					}
					fmt.Fprintf(w, "    %s\t%s\t%s\t%s\n",
						name, a.Status, a.Hostname, a.LocalPath)
				}
				w.Flush()
			} else {
				fmt.Println("  No remote agents connected yet.")
			}
			fmt.Println()

			return nil
		},
	}
}

func newPeerListCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List federated peer hubs",
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()

			conn, err := tryHubConnect()
			if err != nil {
				return fmt.Errorf("cannot connect to hub: %w", err)
			}
			defer conn.Close()

			mux := newCLIMux(ctx, conn)

			resp, err := mux.rpcCall(ctx, "peer.list", nil)
			if err != nil {
				return err
			}
			if resp.Error != nil {
				return fmt.Errorf("hub error: %s", resp.Error.Message)
			}

			data, err := json.Marshal(resp.Result)
			if err != nil {
				return fmt.Errorf("marshal result: %w", err)
			}

			var result struct {
				Peers []protocol.Peer `json:"peers"`
			}
			if err := json.Unmarshal(data, &result); err != nil {
				return fmt.Errorf("parse response: %w", err)
			}

			if len(result.Peers) == 0 {
				fmt.Println("No federated peers.")
				fmt.Println("Use 'bifrost peer new' to generate a magic code.")
				return nil
			}

			w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
			fmt.Fprintf(w, "PEER ID\tNAME\tTRANSPORT\tSTATUS\tLAST SEEN\n")
			for _, p := range result.Peers {
				name := p.DisplayName
				if name == "" {
					name = "-"
				}
				lastSeen := p.LastSeen.Format("2006-01-02 15:04:05")
				fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\n",
					truncateID(p.PeerID, 16), name, p.Transport, p.Status, lastSeen)
			}
			w.Flush()

			return nil
		},
	}
}

// truncateID shortens an ID for display.
func truncateID(id string, maxLen int) string {
	if len(id) <= maxLen {
		return id
	}
	return id[:maxLen-3] + "..."
}
